//! `sirbone demo` — replay a recorded session in the TUI, with no API key and
//! no provider call. The point is the first 30 seconds: see what a run looks
//! like (parallel tools, diffs, verification, the final report) before deciding
//! whether to configure a key.

use std::path::PathBuf;
use std::sync::Arc;

use anyhow::{Context, Result};
use async_trait::async_trait;
use sirbone::agent::{LlmClient, TurnResult};
use sirbone::tools::ToolRegistry;
use sirbone::types::Message;

/// A real sirbone run over `playground/`, recorded as an ordinary session file
/// and scrubbed of local paths. Bundled rather than written by hand on purpose:
/// a made-up transcript would be a claim about the agent's behavior that
/// nothing backs. Regenerate with `scripts/record-demo.sh`.
const RECORDED: &str = include_str!("../../assets/demo-session.jsonl");

/// The prompt the recording script sends. Kept as its own file so the recipe
/// and the artifact cannot drift: the test below checks the bundled recording
/// really starts here. Only the test needs it — at runtime the prompt is
/// already inside the recording.
#[cfg(test)]
const PROMPT: &str = include_str!("../../assets/demo-prompt.txt");

/// Stands in for a provider so the TUI can start without credentials. Replay
/// needs no turns; if the viewer types a prompt, this says why nothing happens
/// instead of failing with a network error.
struct ReplayOnly;

#[async_trait]
impl LlmClient for ReplayOnly {
    async fn run_turn(
        &self,
        _messages: &[&Message],
        _registry: &ToolRegistry,
        _events: &tokio::sync::mpsc::Sender<sirbone::types::AgentEvent>,
        _cancel: &tokio_util::sync::CancellationToken,
    ) -> Result<TurnResult> {
        anyhow::bail!(
            "this is a recorded session, not a live agent — no provider is configured. \
             Run `sirbone login` (or set ANTHROPIC_AUTH_TOKEN / OPENAI_API_KEY) and start \
             `sirbone` for a real run."
        )
    }
}

/// Replay `path` if given, else the bundled recording. The file is always
/// copied into a temp session first: the TUI owns its session path (it appends
/// to it), and a demo must not write into the user's real session history.
pub async fn run_demo(path: Option<PathBuf>) -> Result<()> {
    let jsonl = match &path {
        Some(p) => std::fs::read_to_string(p)
            .with_context(|| format!("cannot read session {}", p.display()))?,
        None => RECORDED.to_string(),
    };
    let session_path =
        std::env::temp_dir().join(format!("sirbone-demo-{}.jsonl", std::process::id()));
    std::fs::write(&session_path, jsonl)
        .with_context(|| format!("cannot write demo session {}", session_path.display()))?;

    let messages: Vec<Message> =
        sirbone::session::collapse(sirbone::session::load(&session_path).await?);
    if messages.is_empty() {
        anyhow::bail!(
            "no messages in {} — a session file records one JSON object per line",
            path.unwrap_or(session_path).display()
        );
    }
    eprintln!(
        "Replaying a recorded run ({} messages). Nothing is sent anywhere; scroll with the mouse \
         or PageUp/PageDown, quit with Ctrl-C.",
        messages.len()
    );

    let mcp_task = tokio::spawn(async { sirbone::mcp::McpLoad::default() });
    let res = sirbone::tui::run_tui(
        "recorded run".into(),
        "demo".into(),
        Arc::new(ReplayOnly),
        ToolRegistry::new(),
        "Replay of a recorded session. No provider is configured.".into(),
        messages,
        session_path.clone(),
        mcp_task,
        false,
    )
    .await;
    let _ = std::fs::remove_file(&session_path);
    res
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The bundled recording has to stay loadable by the ordinary session
    /// reader — it is the same format, not a demo-only dialect — and it must
    /// not carry a real home directory into the crates.io tarball.
    #[tokio::test]
    async fn bundled_recording_loads_and_is_scrubbed() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("demo.jsonl");
        std::fs::write(&path, RECORDED).expect("write");
        let messages = sirbone::session::collapse(
            sirbone::session::load(&path).await.expect("load recording"),
        );
        assert!(
            messages.len() > 5,
            "demo recording too short to show a run: {} messages",
            messages.len()
        );
        assert!(
            !RECORDED.contains("/home/dio"),
            "demo recording still carries the recording machine's home directory"
        );
    }

    /// The asset is generated by `scripts/record-demo.sh`, which sends
    /// `assets/demo-prompt.txt`. Checking the first message against that file
    /// is what keeps recipe and artifact from drifting — including into
    /// another language, which is how the first recording went wrong.
    #[tokio::test]
    async fn bundled_recording_starts_from_the_committed_prompt() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("demo.jsonl");
        std::fs::write(&path, RECORDED).expect("write");
        let messages = sirbone::session::collapse(
            sirbone::session::load(&path).await.expect("load recording"),
        );
        let first = messages.first().expect("recording has no messages");
        assert_eq!(first.role, sirbone::types::Role::User);
        let text = first
            .content
            .iter()
            .filter_map(|b| match b {
                sirbone::types::ContentBlock::Text { text } => Some(text.as_str()),
                _ => None,
            })
            .collect::<String>();
        assert_eq!(
            text.trim(),
            PROMPT.trim(),
            "the recording does not start from assets/demo-prompt.txt — re-record with \
             scripts/record-demo.sh"
        );
    }
}
